name       : skype
version    : 8.86.0.407
release    : 16
source     :
    - https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.86.0.407_amd64.deb : e3a3342583f9401093091a8bb4dcab42c11ce8fb0ae9646cb1be792241baa6ed
homepage   : https://www.skype.com/
license    : Copyright (c) 2019 Skype and/or Microsoft
strip      : no
component  : network.im
summary    : Skype
description: |
    Skype keeps you together. Call, message and share with others.
builddeps  :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
rundeps    :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
setup      : |
    ar xf $sources/skypeforlinux_${version}_amd64.deb
    tar xfz data.tar.gz
    rm -rf opt
install    : |
    mkdir -p $installdir/usr/
    cp -R usr/{bin,share} $installdir/usr/
